package com.emakarovas.animalrescue.persistence.mongo

sealed trait MongoCollectionType

final case object PersonModelCollectionType extends MongoCollectionType
final case object PostingModelCollectionType extends MongoCollectionType
final case object PostingAnimalModelCollectionType extends MongoCollectionType
final case object PostingCommentModelCollectionType extends MongoCollectionType
final case object UserModelCollectionType extends MongoCollectionType
final case object WishModelCollectionType extends MongoCollectionType