package com.emakarovas.animalrescue.model.enumeration

// TODO - keeping this here but currently not using. TBD if used later
sealed trait Country extends ModelEnumeration[Country]
object Country extends ModelEnumeration[Country] {
  case object Afghanistan extends Country
  case object Albania extends Country
  case object Algeria extends Country
  case object Andorra extends Country
  case object Angola extends Country
  case object AntiguaAndBarbuda extends Country
  case object Argentina extends Country
  case object Armenia extends Country
  case object Australia extends Country
  case object Austria extends Country
  case object Azerbaijan extends Country
  case object Bahamas extends Country
  case object Bahrain extends Country
  case object Bangladesh extends Country
  case object Barbados extends Country
  case object Belarus extends Country
  case object Belgium extends Country
  case object Belize extends Country
  case object Benin extends Country
  case object Bhutan extends Country
  case object Bolivia extends Country
  case object BosniaAndHerzegovina extends Country
  case object Botswana extends Country
  case object Brazil extends Country
  case object Brunei extends Country
  case object Bulgaria extends Country
  case object BurkinaFaso extends Country
  case object Burundi extends Country
  case object CaboVerde extends Country
  case object Cambodia extends Country
  case object Cameroon extends Country
  case object Canada extends Country
  case object CentralAfricanRepublic extends Country
  case object Chad extends Country
  case object Chile extends Country
  case object China extends Country
  case object Colombia extends Country
  case object Comoros extends Country
  case object DemocraticRepublicOfTheCongo extends Country
  case object RepublicOfTheCongo extends Country
  case object CostaRica extends Country
  case object CoteDIvoire extends Country
  case object Croatia extends Country
  case object Cuba extends Country
  case object Cyprus extends Country
  case object CzechRepublic extends Country
  case object Denmark extends Country
  case object Djibouti extends Country
  case object Dominica extends Country
  case object DominicanRepublic extends Country
  case object Ecuador extends Country
  case object Egypt extends Country
  case object ElSalvador extends Country
  case object EquatorialGuinea extends Country
  case object Eritrea extends Country
  case object Estonia extends Country
  case object Ethiopia extends Country
  case object Fiji extends Country
  case object Finland extends Country
  case object France extends Country
  case object Gabon extends Country
  case object Gambia extends Country
  case object Georgia extends Country
  case object Germany extends Country
  case object Ghana extends Country
  case object Greece extends Country
  case object Grenada extends Country
  case object Guatemala extends Country
  case object Guinea extends Country
  case object GuineaBissau extends Country
  case object Guyana extends Country
  case object Haiti extends Country
  case object Honduras extends Country
  case object Hungary extends Country
  case object Iceland extends Country
  case object India extends Country
  case object Indonesia extends Country
  case object Iran extends Country
  case object Iraq extends Country
  case object Ireland extends Country
  case object Israel extends Country
  case object Italy extends Country
  case object Jamaica extends Country
  case object Japan extends Country
  case object Jordan extends Country
  case object Kazakhstan extends Country
  case object Kenya extends Country
  case object Kiribati extends Country
  case object Kosovo extends Country
  case object Kuwait extends Country
  case object Kyrgyzstan extends Country
  case object Laos extends Country
  case object Latvia extends Country
  case object Lebanon extends Country
  case object Lesotho extends Country
  case object Liberia extends Country
  case object Libya extends Country
  case object Liechtenstein extends Country
  case object Lithuania extends Country
  case object Luxembourg extends Country
  case object Macedonia extends Country
  case object Madagascar extends Country
  case object Malawi extends Country
  case object Malaysia extends Country
  case object Maldives extends Country
  case object Mali extends Country
  case object Malta extends Country
  case object MarshallIslands extends Country
  case object Mauritania extends Country
  case object Mauritius extends Country
  case object Mexico extends Country
  case object Micronesia extends Country
  case object Moldova extends Country
  case object Monaco extends Country
  case object Mongolia extends Country
  case object Montenegro extends Country
  case object Morocco extends Country
  case object Mozambique extends Country
  case object MyanmarBurma extends Country
  case object Namibia extends Country
  case object Nauru extends Country
  case object Nepal extends Country
  case object Netherlands extends Country
  case object NewZealand extends Country
  case object Nicaragua extends Country
  case object Niger extends Country
  case object Nigeria extends Country
  case object NorthKorea extends Country
  case object Norway extends Country
  case object Oman extends Country
  case object Pakistan extends Country
  case object Palau extends Country
  case object Palestine extends Country
  case object Panama extends Country
  case object PapuaNewGuinea extends Country
  case object Paraguay extends Country
  case object Peru extends Country
  case object Philippines extends Country
  case object Poland extends Country
  case object Portugal extends Country
  case object Qatar extends Country
  case object Romania extends Country
  case object Russia extends Country
  case object Rwanda extends Country
  case object SaintKittsAndNevis extends Country
  case object SaintLucia extends Country
  case object SaintVincentAndTheGrenadines extends Country
  case object Samoa extends Country
  case object SanMarino extends Country
  case object SaoTomeAndPrincipe extends Country
  case object SaudiArabia extends Country
  case object Senegal extends Country
  case object Serbia extends Country
  case object Seychelles extends Country
  case object SierraLeone extends Country
  case object Singapore extends Country
  case object Slovakia extends Country
  case object Slovenia extends Country
  case object SolomonIslands extends Country
  case object Somalia extends Country
  case object SouthAfrica extends Country
  case object SouthKorea extends Country
  case object SouthSudan extends Country
  case object Spain extends Country
  case object SriLanka extends Country
  case object Sudan extends Country
  case object Suriname extends Country
  case object Swaziland extends Country
  case object Sweden extends Country
  case object Switzerland extends Country
  case object Syria extends Country
  case object Taiwan extends Country
  case object Tajikistan extends Country
  case object Tanzania extends Country
  case object Thailand extends Country
  case object TimorLeste extends Country
  case object Togo extends Country
  case object Tonga extends Country
  case object TrinidadAndTobago extends Country
  case object Tunisia extends Country
  case object Turkey extends Country
  case object Turkmenistan extends Country
  case object Tuvalu extends Country
  case object Uganda extends Country
  case object Ukraine extends Country
  case object UnitedArabEmirates extends Country
  case object UnitedKingdom extends Country
  case object UnitedStatesOfAmerica extends Country
  case object Uruguay extends Country
  case object Uzbekistan extends Country
  case object Vanuatu extends Country
  case object VaticanCity extends Country
  case object Venezuela extends Country
  case object Vietnam extends Country
  case object Yemen extends Country
  case object Zambia extends Country
  case object Zimbabwe extends Country
}